[package]
org = "tharanidj"
name = "openapi_dependabot"
version = "0.1.0"
distribution = "2201.13.1"

[build-options]
observabilityIncluded = false

[[dependency]]
org = "ballerina"
name = "data.yaml"
version = "0.8.0"
